//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOMItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BOMItem()
        {
            this.GoodsIssuedItems = new HashSet<GoodsIssuedItem>();
        }
    
        public string BOMItemID { get; set; }
        public string BOMID { get; set; }
        public string ItemID { get; set; }
        public string ItemQty { get; set; }
        public byte BOMItemStatus { get; set; }
    
        public virtual BoM BoM { get; set; }
        public virtual Inventory Inventory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoodsIssuedItem> GoodsIssuedItems { get; set; }
    }
}
