//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourierDelivery
    {
        public string CourierDelID { get; set; }
        public string OutwardDelID { get; set; }
        public string CourierID { get; set; }
    
        public virtual Courier Courier { get; set; }
        public virtual DeliveryNoteOutward DeliveryNoteOutward { get; set; }
    }
}
