//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DefectNotice
    {
        public string DefectNoteID { get; set; }
        public string SupplierID { get; set; }
        public System.DateTime NoticeDate { get; set; }
        public string ItemID { get; set; }
        public int ItemQty { get; set; }
    
        public virtual Supplier Supplier { get; set; }
        public virtual Inventory Inventory { get; set; }
    }
}
