//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryNoteOutward
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DeliveryNoteOutward()
        {
            this.CourierDeliveries = new HashSet<CourierDelivery>();
        }
    
        public string OutwardDelID { get; set; }
        public System.DateTime DelNoteDate { get; set; }
        public string CustomerID { get; set; }
        public string DelTypeID { get; set; }
        public string OrderID { get; set; }
        public string DelStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourierDelivery> CourierDeliveries { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual DelType DelType { get; set; }
    }
}
