//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodsReceiveItem
    {
        public string ReceivedItemID { get; set; }
        public string RecNoteID { get; set; }
        public string InwardDelItemID { get; set; }
        public int ItemQty { get; set; }
    
        public virtual GoodsReceivedNote GoodsReceivedNote { get; set; }
        public virtual InwardDelItem InwardDelItem { get; set; }
    }
}
