//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodsIssuedItem
    {
        public string GoodsIssuedItemID { get; set; }
        public string GoodsIssuedID { get; set; }
        public int ItemQty { get; set; }
        public string BOMItemID { get; set; }
    
        public virtual BOMItem BOMItem { get; set; }
        public virtual GoodsIssued GoodsIssued { get; set; }
    }
}
