//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class InwardDelItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InwardDelItem()
        {
            this.GoodsReceiveItems = new HashSet<GoodsReceiveItem>();
        }
    
        public string InwardDelItemID { get; set; }
        public string InwardDelID { get; set; }
        public string ItemID { get; set; }
        public string ItemQty { get; set; }
        public string Notes { get; set; }
    
        public virtual DeliveryNoteInward DeliveryNoteInward { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoodsReceiveItem> GoodsReceiveItems { get; set; }
        public virtual Inventory Inventory { get; set; }
    }
}
