//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReturnNote
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReturnNote()
        {
            this.ReturnNoteItems = new HashSet<ReturnNoteItem>();
        }
    
        public string ReturnNoteID { get; set; }
        public System.DateTime ReturnDate { get; set; }
        public string ReturnTypeID { get; set; }
        public string IssuedEmployeeID { get; set; }
        public string CustomerID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ReturnType ReturnType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReturnNoteItem> ReturnNoteItems { get; set; }
    }
}
