//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseDataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WarehouseDetailsEntities : DbContext
    {
        public WarehouseDetailsEntities()
            : base("name=WarehouseDetailsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bin> Bins { get; set; }
        public virtual DbSet<BoM> BoMs { get; set; }
        public virtual DbSet<BOMItem> BOMItems { get; set; }
        public virtual DbSet<Courier> Couriers { get; set; }
        public virtual DbSet<CourierDelivery> CourierDeliveries { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<DefectNotice> DefectNotices { get; set; }
        public virtual DbSet<DeliveryNoteInward> DeliveryNoteInwards { get; set; }
        public virtual DbSet<DeliveryNoteOutward> DeliveryNoteOutwards { get; set; }
        public virtual DbSet<DelType> DelTypes { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<EmployeeType> EmployeeTypes { get; set; }
        public virtual DbSet<GoodsIssued> GoodsIssueds { get; set; }
        public virtual DbSet<GoodsIssuedItem> GoodsIssuedItems { get; set; }
        public virtual DbSet<GoodsReceivedNote> GoodsReceivedNotes { get; set; }
        public virtual DbSet<GoodsReceiveItem> GoodsReceiveItems { get; set; }
        public virtual DbSet<Inventory> Inventories { get; set; }
        public virtual DbSet<InwardDelItem> InwardDelItems { get; set; }
        public virtual DbSet<ReturnNote> ReturnNotes { get; set; }
        public virtual DbSet<ReturnNoteItem> ReturnNoteItems { get; set; }
        public virtual DbSet<ReturnType> ReturnTypes { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
    }
}
